- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2024051522193931110000000a.c9msn0vtbfr7.us-east-1.rds.amazonaws.com"
    login_user: "savvytek"
    login_password: "devops123"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', replace: "terraform-2024051522193931110000000a.c9msn0vtbfr7.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', replace: "savvytek" }
    - { regexp: '^tooling', replace: "toolingdb" }
    - { regexp: '^admin', replace: "devops123" }
